CREATE TABLE USER_INFO (
	USER_ID VARCHAR(255), 
	USER_PASS VARCHAR(255), 
	BIRTH_DAY VARCHAR(8), 
	SEX INTEGER, 
	LOCATION VARCHAR, 
	LAST_LOGIN TIMESTAMP, 
	LOGIN_IP VARCHAR(15)
);

ALTER TABLE USER_INFO ADD CONSTRAINT IDX_USER_INFO_PK PRIMARY KEY (USER_ID);
COMMENT ON TABLE 'USER_INFO' IS'«æ?«¶ï×ÜÃ'
COMMENT ON COLUMN 'USER_INFO'.'USER_ID' IS 'ID(Email)';
COMMENT ON COLUMN 'USER_INFO'.'USER_PASS' IS 'PASS';
COMMENT ON COLUMN 'USER_INFO'.'BIRTH_DAY' IS 'ßæÒ´êÅìí';
COMMENT ON COLUMN 'USER_INFO'.'SEX' IS 'àõÜ¬';
COMMENT ON COLUMN 'USER_INFO'.'LOCATION' IS 'ñ¬á¶1';
COMMENT ON COLUMN 'USER_INFO'.'LAST_LOGIN' IS '«í«°«¤«óãÁÊ¾';
COMMENT ON COLUMN 'USER_INFO'.'LOGIN_IP' IS '«í«°«¤«óIP';

