CREATE TABLE USER_INFO (
	USER_ID VARCHAR(255), 
	USER_PASS VARCHAR(255), 
	BIRTH_DAY VARCHAR(8), 
	SEX INTEGER, 
	LOCATION VARCHAR, 
	LAST_LOGIN TIMESTAMP, 
	LOGIN_IP VARCHAR(15)
);

ALTER TABLE USER_INFO ADD CONSTRAINT IDX_USER_INFO_PK PRIMARY KEY (USER_ID);

COMMENT ON TABLE USER_INFO IS  'ユーザ情報';
COMMENT ON COLUMN USER_INFO.USER_ID IS 'ID(Email)';
COMMENT ON COLUMN USER_INFO.USER_PASS IS 'PASS';
COMMENT ON COLUMN USER_INFO.BIRTH_DAY IS '生年月日';
COMMENT ON COLUMN USER_INFO.SEX IS '性別';
COMMENT ON COLUMN USER_INFO.LOCATION IS '住所1';
COMMENT ON COLUMN USER_INFO.LAST_LOGIN IS 'ログイン時刻';
COMMENT ON COLUMN USER_INFO.LOGIN_IP IS 'ログインIP';

CREATE TABLE USER_AUTHENTICATION (
	USER_ID VARCHAR(255), 
	USER_AUTH VARCHAR(1)
);

ALTER TABLE USER_AUTHENTICATION ADD CONSTRAINT IDX_USER_AUTHENTICATION_PK PRIMARY KEY (USER_ID);

COMMENT ON TABLE USER_AUTHENTICATION IS  'ユーザ権限';
COMMENT ON COLUMN USER_AUTHENTICATION.USER_ID IS 'ID(Email)';
COMMENT ON COLUMN USER_AUTHENTICATION.USER_AUTH IS '権限';

