CREATE TABLE USER_INFO (
	USER_ID VARCHAR(255), 
	USER_PASS VARCHAR(255), 
	BIRTH_DAY VARCHAR(8), 
	SEX INTEGER, 
	LOCATION VARCHAR, 
	LAST_LOGIN TIMESTAMP, 
	LOGIN_IP VARCHAR(15)
);

ALTER TABLE USER_INFO ADD CONSTRAINT IDX_USER_INFO_PK PRIMARY KEY (USER_ID);

COMMENT ON TABLE USER_INFO IS 'ユーザ情報'
COMMENT ON COLUMN USER_INFO.USER_ID IS 'ID(Email)';
COMMENT ON COLUMN USER_INFO.USER_PASS IS 'PASS';
COMMENT ON COLUMN USER_INFO.BIRTH_DAY IS '生年月日';
COMMENT ON COLUMN USER_INFO.SEX IS '性別';
COMMENT ON COLUMN USER_INFO.LOCATION IS '住所1';
COMMENT ON COLUMN USER_INFO.LAST_LOGIN IS 'ログイン時刻';
COMMENT ON COLUMN USER_INFO.LOGIN_IP IS 'ログインIP';

CREATE TABLE email_ack (
	SEND_NO INTEGER, 
	SEND_TIME TIMESTAMP NOT NULL, 
	MOTO_JPG_NM VARCHAR, 
	RECV_TIME TIMESTAMP, 
	RECV_CNT INTEGER
);

ALTER TABLE email_ack ADD CONSTRAINT IDX_email_ack_PK PRIMARY KEY (SEND_NO);

COMMENT ON TABLE email_ack IS 'メール受信チェックテーブル'
COMMENT ON COLUMN email_ack.SEND_NO IS '送信番号';
COMMENT ON COLUMN email_ack.SEND_TIME IS '送信時刻';
COMMENT ON COLUMN email_ack.MOTO_JPG_NM IS '元JPGファイル名';
COMMENT ON COLUMN email_ack.RECV_TIME IS '受信時刻';
COMMENT ON COLUMN email_ack.RECV_CNT IS '閲覧回数';

CREATE TABLE USER_AUTHENTICATION (
	USER_ID VARCHAR(255), 
	USER_AUTH VARCHAR(1)
);

ALTER TABLE USER_AUTHENTICATION ADD CONSTRAINT IDX_USER_AUTHENTICATION_PK PRIMARY KEY (USER_ID);

COMMENT ON TABLE USER_AUTHENTICATION IS 'ユーザ権限'
COMMENT ON COLUMN USER_AUTHENTICATION.USER_ID IS 'ID(Email)';
COMMENT ON COLUMN USER_AUTHENTICATION.USER_AUTH IS '権限';

